name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      
      - name: Clone auth-proto
        run: |
          git clone https://github.com/Tim73916/auth-proto.git ../auth-proto
          go mod edit -replace github.com/Tim73916/auth-proto=../auth-proto
      
      - name: Download dependencies
        run: go mod download
      
      - name: Build server
        run: go build -o server ./cmd/sso
      
      - name: Create config directory
        run: |
          mkdir -p config storage
          cp config/local.yaml config/local.yaml
      
      - name: Show config (debug)
        run: cat config/local.yaml
      
      - name: Start gRPC server
        run: |
          ./server --config=./config/local.yaml &
          sleep 5
          netstat -tulpn | grep 50051 || echo "Port 50051 not listening"
      
      - name: Run tests
        run: go test -v ./tests/...